"create-bundle" command: Implement "create-bundle bundle_name proj_dir [proj_dir2 ...]"

diff --git a/setupenv b/setupenv
--- a/setupenv
+++ b/setupenv
@@ -183,6 +183,7 @@ cmd_create_bundle() {
 
     # TODO: -f option which always overwrites $dest.
 
+    local dest_dir="$HOME/.setupenv/bundle"
     case $# in
         0|1)
             if [ -z "$SETUPENV_ID" ]; then
@@ -192,7 +193,6 @@ cmd_create_bundle() {
             fi
 
             local src="$(get_lock_file "$SETUPENV_ID")"
-            local dest_dir="$HOME/.setupenv/bundle"
             if [ $# = 0 ]; then
                 local dest="$dest_dir/$(basename "$src")"
             else
@@ -205,6 +205,14 @@ cmd_create_bundle() {
 
             cp "$src" "$dest"
             echo "Created bundle: $dest"    # TODO: More better filename (prompt to user?)
+            ;;
+        *)
+            local bundle_name="$1"
+            shift
+            echo "$*" >"$dest_dir/$bundle_name" || {
+                echo "Could not write to '$dest_dir/$bundle_name'." >&2
+                exit 1
+            }
             ;;
     esac
 }
